version: "3.8"

networks:
  faynosync_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.25.0.0/16"

services:

  backend:
    extends:
      file: ./docker-compose/services/backend.yml
      service: backend

  s3:
    extends:
      file: ./docker-compose/services/s3.yml
      service: s3

  s3-service:
    extends:
      file: ./docker-compose/services/s3.yml
      service: s3-service

  db:
    extends:
      file: ./docker-compose/services/db.yml
      service: db

  cache:
    extends:
      file: ./docker-compose/services/redis.yml
      service: cache

volumes:
  data:
  data-s3:
  cache:
    driver: local
