version: "3.8"
services:
  mongo:
    image: mongo:4.4
    container_name: server_mongo_database
    restart: always
    volumes:
      - data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=cb_sau_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=MheCk6sSKB1m4xKNw5I
    ports:
      - "27017:27017"

volumes:
  data: