version: "3.8"

services:
  backend:
    build:
      context: ../..
      dockerfile: Dockerfile
    container_name: "faynoSync_backend"
    networks:
      faynosync_network:
        ipv4_address: 172.25.0.6
    ports:
      - "9000:9000"
    volumes:
      -  ../envs/backend.env:/app/.env