version: "3.8"

services:
  db:
    image: mongo:7.0.12
    container_name: "faynoSync_db"
    restart: always
    volumes:
      - data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=cb_faynosync_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=MheCk6sSKB1m4xKNw5I
    ports:
      - "27017:27017"
    networks:
      faynosync_network:
        ipv4_address: 172.25.0.4
